import catchAsyncError from "./catchAsyncError.js";
import axios from "axios";



const isAuthenticated = catchAsyncError(async (req, res, next) => {

})


export default isAuthenticated;